<?php
return array (
  0 => '行分隔符,###',
  1 => '广告管理插件,/addons/AdManager/system.php',
  2 => '系统管理,system/config',
  3 => '视频数据,vod/data',
  4 => '播放器,vodplayer/index',
  5 => '友情链接,link/index',
  6 => '行分隔符,###',
  7 => '色色在线采集,/admins.php/admin/collect/api?ac=list&xt=1&ct=&rday=&cjflag=sszyz&cjurl=http://sscj8.com/inc/sapi.php',
  8 => '玖玖在线采集,/admins.php/admin/collect/api?ac=list&xt=1&ct=&rday=&cjflag=jjzy&cjurl=http://99zywcj.com/inc/sck.php',
  9 => '狼少年在线采集,/admins.php/admin/collect/api?ac=list&xt=1&ct=&rday=&cjflag=lsn&cjurl=http://cjmygzy.com/inc/sapi.php',
  10 => '富二代在线采集,/admins.php/admin/collect/api?ac=list&xt=1&ct=&rday=&cjflag=fu2d&cjurl=http://f2dcj6.com/sapi',
  11 => '字幕网在线采集,/admins.php/admin/collect/api?ac=list&xt=1&ct=&rday=&cjflag=zmw&cjurl=http://zmcj88.com/sapi',
  12 => '久草在线采集,/admins.php/admin/collect/api?ac=list&xt=1&ct=&rday=&cjflag=9czx&cjurl=http://jcspcj8.com/sapi',
  13 => 'JAV名优在线采集,/admins.php/admin/collect/api?ac=list&xt=1&ct=&rday=&cjflag=nyg&cjurl=http://mygzycj.com/sapi.php',
  14 => '利来在线采集,/admins.php/admin/collect/api?ac=list&xt=1&ct=&rday=&cjflag=llzy&cjurl=http://llzxcj.com/inc/sck.php',
  15 => '博天堂伦理采集,/admins.php/admin/collect/api?ac=list&xt=1&ct=&rday=&cjflag=bttcj&cjurl=http://bttcj.com/inc/sapi.php',
  16 => '环亚无码采集,/admins.php/admin/collect/api?ac=list&xt=1&ct=&rday=&cjflag=hymw&cjurl=http://wmcj8.com/inc/sapi.php',
);